#!/bin/bash
yum install unzip wget -y

#Download java
cd /tmp

wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/jav

#install java
rpm -ivh jdk-8u131-linux-x64.rpm

#Download tomcat
wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32-windows-x64.zip
unzip apache-tomcat-8.5.32-windows-x64.zip
mv apache-tomcat-8.5.32 /opt/tomcat
chmod -R 755 /opt/tomcat
#start tomcat service
/opt/tomcat/bin/startup.sh







