#!/usr/bin/env python
import boto3
ec2 = boto3.resource('ec2')
for instance in ec2.instances.all():
    print instance.id, instance.state



To list s3 buckets

import boto3
# Let's use Amazon S3
s3 = boto3.resource('s3')
# Print out bucket names
for bucket in s3.buckets.all():
  print (bucket.name)


#Creating and attaching volume
import boto.ec2

conn = boto.ec2.connect_to_region('us-east-1')

# Create a volume
# create_volume(size, zone, snapshot=None, volume_type=None, iops=None)
vol = conn.create_volume(50, "us-east-1d")
print 'Volume Id: ', vol.id

# Add a Name tag to the new volume so we can find it.
conn.create_tags([vol.id], {"Name":"PyWebDev Example 3"})

#You can check that the volume is now ready and available:
curr_vol = conn.get_all_volumes([vol.id])[0]
print 'Current Volume Status: ', curr_vol.status
print 'Current Volume Zone: ', curr_vol.zone
print 'Current Volume Device: ', curr_vol.attach_data.device

# Since that is pretty boring, let's attach it to a real instance
instance_id = 'i-d8b25cbb'
result = conn.attach_volume (vol.id, instance_id, "/dev/sdy")
print 'Attach Volume Result: ', result
================================================================
